version: '3'

services:
    rabbit:
        image: 'rabbitmq:management'
        ports:
        # The standard AMQP protocol port
            - '5672:5672'
        # HTTP management UI
            - '15672:15672'
        networks:
            - network
    producer:
        depends_on:
            - rabbit
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - rabbit
        command: /usr/local/bin/send.py
        networks:
            - network
    consumer:
        depends_on:
            - rabbit
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - rabbit
        command: /usr/local/bin/fetch.py
        networks:
            - network

networks:
    network: {}
